#https://www.youtube.com/watch?v=xuO8zv62HXM&list=PL0lO_mIqDDFX1c0JHogP5YuZdOVawoepS&index=5

FROM php:7.2-apache

LABEL authors="fisher"

WORKDIR /var/www/html

COPY . /var/www/html/

RUN ls -la /var/www/html/*

EXPOSE 80
